export const GET_ERRORS = "GET_ERRORS";
// User
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
// Events
export const SET_EVENT_LIST = "SET_EVENT_LIST";
export const ADD_EVENT_TO_LIST = "ADD_EVENT_TO_LIST";
export const SET_BOOKING_PAGE = "SET_BOOKING_PAGE";
// Schedule
export const SET_BOOKING_SCHEDULE = "SET_BOOKING_SCHEDULE";
export const SCHEDULE_LOADING = "SCHEDULE_LOADING";
export const SET_SCHEDULE_LIST = "SET_SCHEDULE_LIST";
